@startuml
class Monitor  {
	online : Boolean
	MonitorCompromised : Boolean
	MonitorOS : String
	SoftwareRelease : Integer
	MonitorInfected : Boolean
	void DeviceCompromisesNetwork()
	void NetworkCompromised()
	void MonitorInfectsPLC()
}
class Actuator  {
	online : Boolean
	compromised : Boolean
	void PLCMotorDestroyed()
}
class Malware  {
	CompatablePLCOS : String
	void MonitorInfectsPLC()
}
class Sensor  {
	online : Boolean
	compromised : Boolean
}
class ContainableByAny  {
}
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	online : Boolean
	NetworkCompromised : Boolean
	void DeviceCompromisesNetwork()
	void NetworkCompromised()
	void MonitorInfectsPLC()
}
class PLC  {
	online : Boolean
	compromised : Boolean
	PLCOS : String
	SoftwareRelease : Integer
	Infected : Boolean
	void PLCMotorDestroyed()
	void MonitorInfectsPLC()
}
class Any  {
}
class IndustrialComponent  {
	online : Boolean
	compromised : Boolean
}

Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : Connector
Actuator -> "*" IndustrialComponent : ChildComponent
Malware -> "*" Monitor : InfectedMonitors
Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC
ContainableByAny -> "0..1" Any : containedBy
NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
PLC -> "*" NetworkConnector : Connector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
IndustrialComponent -> "*" Sensor : ParentSensor

Monitor -up-|>  Any
Actuator -up-|>  Any
Malware -up-|>  Any
Sensor -up-|>  Any
NetworkConnector -up-|>  Any
PLC -up-|>  Any
IndustrialComponent -up-|>  Any
@enduml
