@startuml
title RuntimeData and behavior
class PLC  {
}
class Sensor  {
}
class Any  {
}
class NetworkConnector  {
	NetworkCompromised(, PrimaryMonitor : **Monitor**, )
	MonitorInfectsPLC(, InfectedMonitor : **Monitor**, VictimPLC : **PLC**, )
	DeviceInfectsNetwork(, InfectedMonitor : **Monitor**, )
}
class Actuator  {
	PLCMotorDestroyed(, CompromisedPLC : **PLC**, )
}
class ContainableByAny  {
}
class Monitor  {
}
class IndustrialComponent  {
}


PLC -up-|>  Any
Sensor -up-|>  Any
NetworkConnector -up-|>  Any
Actuator -up-|>  Any
Monitor -up-|>  Any
IndustrialComponent -up-|>  Any
@enduml
