@startuml
class Sensor  {
	SensorOnline : Boolean
	SensorCompromised : Boolean
}
class Actuator  {
	ActuatorOnline : Boolean
	ActuatorCompromised : Boolean
	void ReactorMotorDestroyed()
	void SafeGuardsDeactivateCompromisedSystem()
}
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	ConnectorOnline : Boolean
	NetworkCompromised : Boolean
	void DeviceCompromisesNetwork()
	void MonitorInfectsPLC()
	void NetworkCompromised()
}
class Monitor  {
	MonitorOnline : Boolean
	MonitorCompromised : Boolean
	MonitorOS : String
	SoftwareRelease : Integer
	MonitorInfected : Boolean
	void DeviceCompromisesNetwork()
	void MonitorInfectsPLC()
	void NetworkCompromised()
}
class PLC  {
	PLCOnline : Boolean
	PLCCompromised : Boolean
	PLCOS : String
	SoftwareRelease : Integer
	PLCInfected : Boolean
	void ReactorMotorDestroyed()
	void MonitorInfectsPLC()
}
class SafeguardSystem  {
	SafeguardOnline : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
}
class Malware  {
	CompatableSoftwareDate : Integer
	CompatableMonitorOS : String
	CompatablePLCOS : String
	void MonitorInfectsPLC()
	void NetworkCompromised()
}
class Any  {
}
class ContainableByAny  {
}
class IndustrialComponent  {
	ComponentOnline : Boolean
	ComponentCompromised : Boolean
}

Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC
Actuator -> "*" IndustrialComponent : ChildComponent
NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : MonitorConnector
PLC -> "*" NetworkConnector : PLCConnector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
Malware -> "*" Monitor : InfectedMonitors
ContainableByAny -> "0..1" Any : containedBy
IndustrialComponent -> "*" Sensor : ParentSensor

Sensor -up-|>  Any
Actuator -up-|>  Any
NetworkConnector -up-|>  Any
Monitor -up-|>  Any
PLC -up-|>  Any
SafeguardSystem -up-|>  Any
Malware -up-|>  Any
IndustrialComponent -up-|>  Any
@enduml
