@startuml
class Actuator  {
	ActuatorOnline : Boolean
	ActuatorCompromised : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
	void ReactorMotorDestroyed()
}
class IndustrialComponent  {
	ComponentOnline : Boolean
	ComponentCompromised : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
}
class SensitiveFile  {
	void UploadAndDeleteSecretFiles()
}
class PLC  {
	PLCOnline : Boolean
	PLCCompromised : Boolean
	PLCOS : String
	PLCSoftwareRelease : Integer
	PLCInfected : Boolean
	void MonitorInfectsPLC()
	void ReactorMotorDestroyed()
}
class Any  {
}
class SensitiveFile  {
	void UploadAndDeleteSecretFiles()
}
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	ConnectorOnline : Boolean
	NetworkCompromised : Boolean
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
	void MonitorInfectsPLC()
	void DeviceCompromisesNetwork()
}
class Monitor  {
	MonitorOnline : Boolean
	MonitorCompromised : Boolean
	MonitorOS : String
	MonitorSoftwareRelease : Integer
	MonitorInfected : Boolean
	SoftwarePresent : String
	IP : String
	void OperatorOpensPhishingEmail()
	void MonitorInfectsPLC()
	void UploadAndDeleteSecretFiles()
	void DeviceCompromisesNetwork()
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
	void HWPExploitUsed()
}
class Malware  {
	OwnerIP : String
	CompatableSoftwareDate : Integer
	CompatableMonitorOS : String
	CompatablePLCOS : String
	RequiredSoftware : String
	void HWPExploitUsed()
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
	void OperatorOpensPhishingEmail()
	void MonitorInfectsPLC()
	void DeviceCompromisesNetwork()
	void UploadAndDeleteSecretFiles()
}
class Sensor  {
	SensorOnline : Boolean
	SensorCompromised : Boolean
}
class PLC  {
	PLCOnline : Boolean
	PLCCompromised : Boolean
	PLCOS : String
	PLCSoftwareRelease : Integer
	PLCInfected : Boolean
	void MonitorInfectsPLC()
	void ReactorMotorDestroyed()
}
class Operator  {
	PhishingEmailReceived : Boolean
	PhishingEmailOpened : Boolean
	Email : String
	TrustedEmails : String
	isHacker : Boolean
	void HWPExploitUsed()
	void HackerSendsPhishingEmail()
	void OperatorOpensPhishingEmail()
}
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	ConnectorOnline : Boolean
	NetworkCompromised : Boolean
	void MonitorInfectsPLC()
	void DeviceCompromisesNetwork()
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
}
class Sensor  {
	SensorOnline : Boolean
	SensorCompromised : Boolean
}
class Malware  {
	OwnerIP : String
	CompatableSoftwareDate : Integer
	CompatableMonitorOS : String
	CompatablePLCOS : String
	RequiredSoftware : String
	void OperatorOpensPhishingEmail()
	void MonitorInfectsPLC()
	void UploadAndDeleteSecretFiles()
	void DeviceCompromisesNetwork()
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
	void HWPExploitUsed()
}
class SafeguardSystem  {
	SafeguardOnline : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
}
class IndustrialComponent  {
	ComponentOnline : Boolean
	ComponentCompromised : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
}
class ContainableByAny  {
}
class SafeguardSystem  {
	SafeguardOnline : Boolean
	void SafeGuardsDeactivateCompromisedSystem()
}
class Actuator  {
	ActuatorOnline : Boolean
	ActuatorCompromised : Boolean
	void ReactorMotorDestroyed()
	void SafeGuardsDeactivateCompromisedSystem()
}
class Operator  {
	PhishingEmailReceived : Boolean
	PhishingEmailOpened : Boolean
	Email : String
	TrustedEmails : String
	isHacker : Boolean
	void OperatorOpensPhishingEmail()
	void HackerSendsPhishingEmail()
	void HWPExploitUsed()
}
class Monitor  {
	MonitorOnline : Boolean
	MonitorCompromised : Boolean
	MonitorOS : String
	MonitorSoftwareRelease : Integer
	MonitorInfected : Boolean
	SoftwarePresent : String
	IP : String
	void HWPExploitUsed()
	void NetworkCompromised()
	void HackerSendsPhishingEmail()
	void OperatorOpensPhishingEmail()
	void MonitorInfectsPLC()
	void DeviceCompromisesNetwork()
	void UploadAndDeleteSecretFiles()
}

Actuator -> "*" IndustrialComponent : ChildComponent
IndustrialComponent -> "*" Sensor : ParentSensor
SensitiveFile -> "*" Monitor : ExistsOnMonitors
SensitiveFile -> "*" Malware : CompromisedByMalware
PLC -> "*" NetworkConnector : PLCConnector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
SensitiveFile -> "*" Monitor : ExistsOnMonitors
SensitiveFile -> "*" Malware : CompromisedByMalware
NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
NetworkConnector -> "*" NetworkConnector : LinkedNetworkConnectors
Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : MonitorConnector
Malware -> "*" Monitor : InfectedMonitors
Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC
PLC -> "*" NetworkConnector : PLCConnector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
Operator -> "1" Monitor : OperatesMonitor
NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
NetworkConnector -> "*" NetworkConnector : LinkedNetworkConnectors
Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC
Malware -> "*" Monitor : InfectedMonitors
IndustrialComponent -> "*" Sensor : ParentSensor
ContainableByAny -> "0..1" Any : containedBy
Actuator -> "*" IndustrialComponent : ChildComponent
Operator -> "1" Monitor : OperatesMonitor
Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : MonitorConnector

Actuator -up-|>  Any
IndustrialComponent -up-|>  Any
SensitiveFile -up-|>  Any
PLC -up-|>  Any
SensitiveFile -up-|>  Any
NetworkConnector -up-|>  Any
Monitor -up-|>  Any
Malware -up-|>  Any
Sensor -up-|>  Any
PLC -up-|>  Any
Operator -up-|>  Any
NetworkConnector -up-|>  Any
Sensor -up-|>  Any
Malware -up-|>  Any
SafeguardSystem -up-|>  Any
IndustrialComponent -up-|>  Any
SafeguardSystem -up-|>  Any
Actuator -up-|>  Any
Operator -up-|>  Any
Monitor -up-|>  Any
@enduml
