@startuml
title RuntimeData and behavior
class IndustrialComponent  {
}
class Operator  {
	OperatorOpensPhishingEmail(, ComputerOfTarget : **Monitor**, ComputerOfHacker : **Monitor**, Hacker : **Operator**, PhishingVirus : **Malware**, )
	HackerSendsPhishingEmail(, TargetMonitor : **Monitor**, MConnector : **NetworkConnector**, EmailServer : **NetworkConnector**, PhishingMalware : **Malware**, HackerOperator : **Operator**, HackerMonitor : **Monitor**, HackerWifi : **NetworkConnector**, )
}
class Actuator  {
	ReactorMotorDestroyed(, CompromisedPLC : **PLC**, )
}
class Sensor  {
}
class NetworkConnector  {
	NetworkCompromised(, PrimaryMonitor : **Monitor**, CulpritMalware : **Malware**, )
	DeviceCompromisesNetwork(, InfectedMonitor : **Monitor**, CulpritMalware : **Malware**, )
	MonitorInfectsPLC(, InfectedMonitor : **Monitor**, VictimPLC : **PLC**, AMalware : **Malware**, )
}
class Malware  {
}
class SafeguardSystem  {
	SafeGuardsDeactivateCompromisedSystem(, CompromisedActuator : **Actuator**, ActuatorComponent : **IndustrialComponent**, )
}
class NetworkConnector  {
	DeviceCompromisesNetwork(, InfectedMonitor : **Monitor**, CulpritMalware : **Malware**, )
	MonitorInfectsPLC(, InfectedMonitor : **Monitor**, VictimPLC : **PLC**, AMalware : **Malware**, )
	NetworkCompromised(, PrimaryMonitor : **Monitor**, CulpritMalware : **Malware**, )
}
class PLC  {
}
class ContainableByAny  {
}
class IndustrialComponent  {
}
class SafeguardSystem  {
	SafeGuardsDeactivateCompromisedSystem(, CompromisedActuator : **Actuator**, ActuatorComponent : **IndustrialComponent**, )
}
class Monitor  {
}
class Any  {
}
class Actuator  {
	ReactorMotorDestroyed(, CompromisedPLC : **PLC**, )
}
class Sensor  {
}
class Operator  {
	HackerSendsPhishingEmail(, TargetMonitor : **Monitor**, MConnector : **NetworkConnector**, EmailServer : **NetworkConnector**, PhishingMalware : **Malware**, HackerOperator : **Operator**, HackerMonitor : **Monitor**, HackerWifi : **NetworkConnector**, )
	OperatorOpensPhishingEmail(, ComputerOfTarget : **Monitor**, ComputerOfHacker : **Monitor**, Hacker : **Operator**, PhishingVirus : **Malware**, )
}
class Malware  {
}
class SensitiveFile  {
}
class Monitor  {
}
class PLC  {
}
class SensitiveFile  {
}


IndustrialComponent -up-|>  Any
Operator -up-|>  Any
Actuator -up-|>  Any
Sensor -up-|>  Any
NetworkConnector -up-|>  Any
Malware -up-|>  Any
SafeguardSystem -up-|>  Any
NetworkConnector -up-|>  Any
PLC -up-|>  Any
IndustrialComponent -up-|>  Any
SafeguardSystem -up-|>  Any
Monitor -up-|>  Any
Actuator -up-|>  Any
Sensor -up-|>  Any
Operator -up-|>  Any
Malware -up-|>  Any
SensitiveFile -up-|>  Any
Monitor -up-|>  Any
PLC -up-|>  Any
SensitiveFile -up-|>  Any
@enduml
