@startuml
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	ConnectorOnline : Boolean
	NetworkCompromised : Boolean
}
class Monitor  {
	MonitorOnline : Boolean
	MonitorCompromised : Boolean
	MonitorOS : String
	MonitorSoftwareRelease : Integer
	MonitorInfected : Boolean
}
class PLC  {
	PLCOnline : Boolean
	PLCCompromised : Boolean
	PLCOS : String
	PLCSoftwareRelease : Integer
	PLCInfected : Boolean
}
class IndustrialComponent  {
	ComponentOnline : Boolean
	ComponentCompromised : Boolean
}
class Actuator  {
	ActuatorOnline : Boolean
	ActuatorCompromised : Boolean
}
class Sensor  {
	SensorOnline : Boolean
	SensorCompromised : Boolean
}
class Malware  {
	CompatableSoftwareDate : Integer
	CompatableMonitorOS : String
	CompatablePLCOS : String
}
class SafeguardSystem  {
	SafeguardOnline : Boolean
}

NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : MonitorConnector
PLC -> "*" NetworkConnector : PLCConnector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
IndustrialComponent -> "*" Sensor : ParentSensor
Actuator -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC
Malware -> "*" Monitor : InfectedMonitors

NetworkConnector -up-|>  Any
Monitor -up-|>  Any
PLC -up-|>  Any
IndustrialComponent -up-|>  Any
Actuator -up-|>  Any
Sensor -up-|>  Any
Malware -up-|>  Any
SafeguardSystem -up-|>  Any
@enduml
