@startuml
class NetworkConnector  {
	trafficLevel : Integer
	trafficCapacity : Integer
	online : Boolean
	compromised : Boolean
}
class Monitor  {
	online : Boolean
	compromised : Boolean
}
class PLC  {
	online : Boolean
	compromised : Boolean
}
class IndustrialComponent  {
	online : Boolean
	compromised : Boolean
}
class Actuator  {
	online : Boolean
	compromised : Boolean
}
class Sensor  {
	online : Boolean
	compromised : Boolean
}

NetworkConnector -> "*" PLC : PLCs
NetworkConnector -> "*" Monitor : Monitors
Monitor -> "*" Monitor : SiblingMonitor
Monitor -> "*" NetworkConnector : Connector
PLC -> "*" NetworkConnector : Connector
PLC -> "*" Actuator : ChildActuator
PLC -> "*" Sensor : ChildSensor
IndustrialComponent -> "*" Sensor : ParentSensor
Actuator -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" IndustrialComponent : ChildComponent
Sensor -> "*" PLC : ParentPLC

NetworkConnector -up-|>  Any
Monitor -up-|>  Any
PLC -up-|>  Any
IndustrialComponent -up-|>  Any
Actuator -up-|>  Any
Sensor -up-|>  Any
@enduml
