@startuml
object "Ethernet : NetworkConnector" as Ethernet #Wheat
object "ControlRoomOperator : Operator" as ControlRoomOperator #Wheat
object "KimsukyHacker : Operator" as KimsukyHacker #Wheat
object "KimsukyMonitor : Monitor" as KimsukyMonitor #Wheat
object "DiagnosticsOperator : Operator" as DiagnosticsOperator #Wheat
object "ExternalEmailServer : NetworkConnector" as ExternalEmailServer #Wheat
object "HackerWifi : NetworkConnector" as HackerWifi #Wheat
object "HANGMAN : Malware" as HANGMAN #LightBlue
object "ControlRoom : Monitor" as ControlRoom #Wheat
object "Diagnostics : Monitor" as Diagnostics #Wheat
object "DataAcquisition : Monitor" as DataAcquisition #Wheat
object "TurbineController : PLC" as TurbineController #Aquamarine
object "SteamFlowController : PLC" as SteamFlowController #Aquamarine
object "FeedwaterController : PLC" as FeedwaterController #Aquamarine
object "ReactorController : PLC" as ReactorController #Aquamarine
object "ReactorSensor : Sensor" as ReactorSensor #LightBlue
object "ReactorActuator : Actuator" as ReactorActuator #LightBlue
object "FeedwaterSensor : Sensor" as FeedwaterSensor #LightBlue
object "FeedwaterActuator : Actuator" as FeedwaterActuator #LightBlue
object "SteamFlowSensor : Sensor" as SteamFlowSensor #LightBlue
object "SteamFlowActuator : Actuator" as SteamFlowActuator #LightBlue
object "TurbineSensor : Sensor" as TurbineSensor #LightBlue
object "TurbineActuator : Actuator" as TurbineActuator #LightBlue
object "Turbine : IndustrialComponent" as Turbine #lavender
object "Reactor : IndustrialComponent" as Reactor #lavender
object "Pipe : IndustrialComponent" as Pipe #lavender
object "SteamGenerator : IndustrialComponent" as SteamGenerator #lavender
object "SafeGuarding : SafeguardSystem" as SafeGuarding #Aquamarine
object "KHNPNuclearSecrets : SensitiveFile" as KHNPNuclearSecrets 
Diagnostics -> Ethernet : MonitorConnector
ControlRoom -> Ethernet : MonitorConnector
DataAcquisition -> Ethernet : MonitorConnector
Ethernet --> ReactorController : PLCs
ReactorController --> ReactorActuator : ChildActuator
ReactorController -up-> Ethernet : PLCConnector
ReactorActuator --> Reactor : ChildComponent
ReactorController --> ReactorSensor : ChildSensor
ReactorSensor -up-> ReactorController : ParentPLC
ReactorSensor --> Reactor : ChildComponent
Reactor -up-> ReactorSensor : ParentSensor
Ethernet -> ControlRoom : Monitors
Ethernet -> DataAcquisition : Monitors
Ethernet -> Diagnostics : Monitors
Diagnostics -> ControlRoom : SiblingMonitor
Diagnostics -> DataAcquisition : SiblingMonitor
DataAcquisition -> Diagnostics : SiblingMonitor
DataAcquisition -> ControlRoom : SiblingMonitor
ControlRoom -> Diagnostics : SiblingMonitor
ControlRoom -> DataAcquisition : SiblingMonitor
Ethernet --> TurbineController : PLCs
Ethernet --> SteamFlowController : PLCs
Ethernet --> FeedwaterController : PLCs
TurbineController -up-> Ethernet : PLCConnector
SteamFlowController -up-> Ethernet : PLCConnector
FeedwaterController -up-> Ethernet : PLCConnector
TurbineController --> TurbineActuator : ChildActuator
FeedwaterController --> FeedwaterActuator : ChildActuator
SteamFlowController --> SteamFlowActuator : ChildActuator
SteamFlowController --> SteamFlowSensor : ChildSensor
TurbineController --> TurbineSensor : ChildSensor
FeedwaterController --> FeedwaterSensor : ChildSensor
FeedwaterActuator --> Pipe : ChildComponent
SteamFlowActuator --> SteamGenerator : ChildComponent
TurbineActuator --> Turbine : ChildComponent
TurbineSensor --> Turbine : ChildComponent
SteamFlowSensor --> SteamGenerator : ChildComponent
FeedwaterSensor --> Pipe : ChildComponent
FeedwaterSensor -up-> FeedwaterController : ParentPLC
SteamFlowSensor -up-> SteamFlowController : ParentPLC
TurbineSensor -up-> TurbineController : ParentPLC
Pipe -up-> FeedwaterSensor : ParentSensor
Turbine -up-> TurbineSensor : ParentSensor
SteamGenerator -up-> SteamFlowSensor : ParentSensor
Ethernet -> ExternalEmailServer : LinkedNetworkConnectors
ExternalEmailServer -> HackerWifi : LinkedNetworkConnectors
ExternalEmailServer -> Ethernet : LinkedNetworkConnectors
KHNPNuclearSecrets -up-> ControlRoom : ExistsOnMonitors
ControlRoomOperator -> ControlRoom : OperatesMonitor
KimsukyHacker -> KimsukyMonitor : OperatesMonitor
KimsukyMonitor -> HackerWifi : MonitorConnector
HackerWifi -> KimsukyMonitor : Monitors
HackerWifi -> ExternalEmailServer : LinkedNetworkConnectors
DiagnosticsOperator -> Diagnostics : OperatesMonitor
@enduml
